version: '2'
services:
    app:
        image: daocloud.io/guodong/cloudwarelabs-api:latest
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "DB_DATABASE=cloudwarelabs"
    database:
        image: mysql:5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=cloudwarelabs"