FROM php:7
RUN apt-get update
RUN apt-get install -y php5-curl php5-mysql
ADD . /var/www/laravel
RUN chmod -R 777 /var/www/laravel/storage && chmod -R 777 /var/www/laravel/bootstrap/cache
EXPOSE 80
WORKDIR /var/www/laravel
CMD [ "php", "artisan", "serve", "--host", "0.0.0.0"]